### ISSUE TITLE
Not working on Windows

### ISSUE THREAD

**Issue by ghost** [ahmedam55/sassSolution#1]
Thanks for your package. It's very good idea, but it seems not working, for me at least. Should I provide any additional settings? I use https://github.com/hudochenkov/Syntax-highlighting-for-PostCSS for syntax highlighting.

**Comment by ahmedam55** [comment]
I actually created it using windows and then supported mac.

Can you please be more specific about the bug you are facing?

**Comment by ghost** [comment]
I add `variables.scss` file to the autocomplete cache via sidebar context menu, close this file, and open for example main.scss, but when autocomplete triggers there is no variables from `variables.scss`.

ST 3114

**Comment by ahmedam55** [comment]
can you please send me a sample project that is not working 
and I will check it 

Thank you

**Comment by ghost** [comment]
I found solution. Missing scope for SCSS, when you are using [POSTCSS Highlighting](https://github.com/hudochenkov/Syntax-highlighting-for-PostCSS) for SCSS files.

**Comment by ghost** [comment]
Thanks a lot! Amazing plugin :wink:

**Comment by ghost** [comment]
Also it seems autocomplete isn't working until you save open view.

**Comment by ahmedam55** [comment]
autocomplete works whenever you type 
but the engine will not process the new code until you save 
I'm happy that your problem is solved.
