### ISSUE TITLE
Not working with SCSS syntax

### ISSUE THREAD

**Issue by ivancuric** [ahmedam55/sassSolution#4]
Using ST3 3120 with Syntax Highlighting For Sass. After adding files to watch nothing appears in the autocompete popup.

**Comment by ahmedam55** [comment]
@ivancuric 
I'm afraid it's working for SCSS syntax only for now,
Although I plan to extend it to sass syntax in the future.
So sorry for your inconvenience.

**Comment by ivancuric** [comment]
My bad, I meant SCSS :) Using https://github.com/P233/Syntax-highlighting-for-Sass
![image](https://cloud.githubusercontent.com/assets/2827047/17584839/0df844be-5fb9-11e6-83fc-9b1b502d7c04.png)

Maybe it has something to do with that package's autocomplete? Which package are you using for SCSS?

**Comment by ahmedam55** [comment]
It shouldn't be a problem,
Can you please show me your scope
`Tools=>Developer=>Show Scope Name`

**Comment by ivancuric** [comment]
```
source.scss keyword.control.at-rule.css.sass
```

**Comment by ahmedam55** [comment]
Do your files end with `.scss` ?

**Comment by ivancuric** [comment]
Yep.

**Comment by ahmedam55** [comment]
okay let's take a step back 
Are you sure you followed those steps:
1. Opened the project in SublimeText.
2. Right click on your SCSS directory to add it to SassSolution Auto completion folder's list.
3. Opened any scss file in that directory and saved it.
4. Tried to write any mixin or variable to see the auto complete list.

**Comment by ivancuric** [comment]
Ok, added both the folder with the partials, and specific files:
![image](https://cloud.githubusercontent.com/assets/2827047/17643364/846c0026-6168-11e6-8a6e-614b95cfa4e9.png)
![image](https://cloud.githubusercontent.com/assets/2827047/17643365/88c39e7c-6168-11e6-8e00-cd8798a84e6b.png)

And nothing happens:
![image](https://cloud.githubusercontent.com/assets/2827047/17643366/90c67aae-6168-11e6-8c72-346f5b9c952e.png)
:(

**Comment by ahmedam55** [comment]
maybe somehow sublime is interpreting that file as sass file as you can notice the icon of the file saying `sass`

**Comment by ahmedam55** [comment]
btw, you don't have to add two folders,
you can just add the parent and the package will work recursively.

**Comment by ivancuric** [comment]
Which package did you use for scss? The Sass icon is that of the Material Theme.

**Comment by ahmedam55** [comment]
yes the sass icon is coming from material theme

**Comment by ivancuric** [comment]
Works! I only needed to add the root folder where all my `.scss` files are. Adding child folders and files which contain just the variables didn't work. You might want to emphasise that in the readme.

Thanks for the troubleshooting!
