### ISSUE TITLE
Looks awesome but autocompletition doesn't work.

### ISSUE THREAD

**Issue by golaod** [ahmedam55/sassSolution#5]
I did exactly the same thing as on screencast. Created 2 files, added one to files array and nothing. Added both, nothing. Added directory and...still nothing.

**Comment by ahmedam55** [comment]
can you please take a look on that issue 
https://github.com/ahmedam55/SassSolution/issues/4

**Comment by ahmedam55** [comment]
@golaod 
Everything is alright with you?

**Comment by golaod** [comment]
Sorry for lack of info, but I was sick :/
Regarding solution in #4, it didn't help. I added parent folder, grandparent, I even added the root folder and still nothing. I disabled CodeIntel, because I thought maybe it would block autocompletition, but no.

As reference, my scope says: source.sass

**Comment by ahmedam55** [comment]
No worries,
Is your scope ia saying sass, but it's scss code or it's sass code?

**Comment by ahmedam55** [comment]
Because supporting sass syntax is a future item list.

**Comment by golaod** [comment]
Scss.

`@mixin my-test($qwe) {
    color: $qwe;
}
`

**Comment by golaod** [comment]
When you asked that question, then I removed sass and installed scss instead. Changed scope for 2 files and saved them, then it started to work. In that case, it looks like your plugin requires to have scss scope, but it doesn't add it to sublime.
