### ISSUE TITLE
Further development

### ISSUE THREAD

**Issue by SassNinja** [ahmedam55/sassSolution#6]
it this package still getting developed further?

It took me about an hour to get the autocompletion running (the doc should be more clear).
After changing my .scss file to scss syntax (I prefer the sass syntax for .scss files because my theme looks better then) and adding the project root folder, autocomplete works partially.
But nevertheless not all variables seems to be found and I'm missing more autocomplete features (not only extend, but also functions).

Since there doesn't seem to be many good sass autocomplete packages for SL out there (yours seems to be the best) I'm considering using another editor than SL...

Do you have any plans to continue the development of this package?

**Comment by ahmedam55** [comment]
Firstly, I have to thank you for that super helpful pull request and thanks for your effort.

Secondly, yes I have plans to continue developing this package. Please send me more details about each issue you've faced and your OS, SublimeText version and so on. If you could send me a code sample that reproduce the issue it'd be amazing.

Thank you so much

**Comment by SassNinja** [comment]
thanks for your quick reply! I'm glad to hear you want to continue the development of this package :-)

Attached you can find a quick scss test setup I've just created so you can reproduce my issues and understand what I mean.

- [BUG] when using several maps, only the first one gets suggested ($other-... or $test-... doesn't do anything)
- [FEATURE] functions are not supported yet, are they? would be really nice to get the same autocomplete as for mixins (I know there's no @include you can use as trigger here but maybe a starting round bracket can be used?)
- [IMPROVEMENT] if the suggested variable is a map, it would be great to see the included keys/values in the suggestion
- [IMPROVEMENT] support of a local config file would be great since I don't want to always adjust the user settings (not all projects share the same files so it doesn't make sense to suggest mixins that can't be used in the current project)
- [FEATURE] sass syntax support (my theme 'cyanide' just looks better then + it would make the package 'complete')

I think that's it what has come in my mind so far. If you prefer I can break the list down in individual tickets/issues.

Surprisingly it works in the attached, simplified setup quite well. In my large project the autocomplete doesn't work that reliable and doesn't find all variables/mixins that are available.
Unfortunately I can't send the project files to you. But I can tell you that most of my projects use the framework 'zurb foundation'. Maybe you can test it yourself (or I will prepare another test setup when I have some time).

Best regards
Kai

[sasssolution_tests.zip](https://github.com/ahmedam55/SassSolution/files/763196/sasssolution_tests.zip)

**Comment by SassNinja** [comment]
Regarding your question about my OS & SL version:

I'm using SublimeText 3 (Build 3126) on Mac OS X 10.11.5

My installed, sass related packages are:
- Sass
- SassSolution
- SassyComments
- SCSS

**Comment by ahmedam55** [comment]
Regarding The map bug it's actual not an issue but we can call it an important feature, as for now it autocompletes only variables and mixins.

So what I need to do is to start support:
1. Maps autocomplete with values and keys (can be very tricky).
2. Functions
3.Sass syntax

_[IMPROVEMENT] support of a local config file would be great since I don't want to always adjust the user settings (not all projects share the same files so it doesn't make sense to suggest mixins that can't be used in the current project)_

Regarding that point, **it won't happen** as it checks which project are you in and scans the files of that project that you added earlier to be autocompleted 

I will check Zurb project, but the thing is that I use it constantly in my large projects and it's working perfectly and autocompleting all the vars and mixins I have.

Thank you Kai for you precious feedback. I really appreciate that.

**Comment by SassNinja** [comment]
ok, regarding maps aren't supported yet, it's indeed a feature and not a bug.
but I think you got me :-)
so the most important new features are:
- maps support
- functions support

(sass syntax would be great, but I think it's not a must have)

Good to hear the package already considers the current project and not uses all paths for all projects. I have to admit I did't check that but just saw there's no way to define project based paths.

Interesting that you haven't had any problems with large projects. I'm not sure if my problems are caused by the [framework](http://foundation.zurb.com/sites/download.html/) or by our setup. I will definitely get to the bottom of this and try to reproduce the issues with example code.

**Comment by ahmedam55** [comment]
I added support for functions. Still the support for maps would be kind of tricky.

**Comment by SassNinja** [comment]
Great to hear, functions are supported now!

But would you please tell me how to use autocomplete for functions?
I tested it with the test setup I've sent you (see above) and it didn't work. The autocomplete didn't recognize the "isSmall" function (only the $size parameter without reference to the function).

Regarding the map feature:
Can you go in detail what part of the map support is tricky/difficult? I'm not familiar with python but maybe I can give you some help with the pattern (if that's the problem)

**Comment by ahmedam55** [comment]
Can you please try now? I pushed a change that might fix your issue.

**Comment by ahmedam55** [comment]
Regarding the map feature:
It can be tricky because technically it can be in written in different styles in addition to me not using it at my work, so I can't catch the bugs of my package regarded predicting it.
