### ISSUE TITLE
Settings file location

### ISSUE THREAD

**Issue by floq-design** [ahmedam55/sassSolution#8]
Hi
Just found your plugin and so far it's working nicely.
#### Question regarding the settings file.
Wouldn't it make more sense for paths to be saved either in the project file ie `project.sublime-project` or maybe as a `.sasssolutions` file in the project root?

The reason I suggest this is I assume **SassSolutions** 'watches' the files in the folder paths defined.. so when I've added more projects to the current settings file, I'll be given suggestions of classes and mixins etc from other projects... or am I misunderstanding how it works?
Cheers
James

**Comment by ahmedam66** [comment]
Actually it checks **which project is open** now and only gives you the completion of that project.

I prefer to make it a setting in the editor itself, so you don't add useless files to the repo, as other people may not be interested even in SublimeText itself.

**Comment by ahmedam55** [comment]
Actually it checks **which project is open** now and only gives you the completion of that project.

I prefer to make it a setting in the editor itself, so you don't add useless files to the repo, as other people may not be interested even in SublimeText itself.
